import React, { useState, useEffect } from 'react';
import WorkflowVisualization from './WorkflowVisualization';
import LoadingSpinner from './LoadingSpinner';
import PostPreview from './PostPreview';
import PlatformSelector from './PlatformSelector';
import ToastNotification from './ToastNotification';
import AIAssistant from './AIAssistant';
import UserProfile from './UserProfile';

const Dashboard = () => {
  const [topic, setTopic] = useState('');
  const [generatedPost, setGeneratedPost] = useState('');
  const [generatedImageUrl, setGeneratedImageUrl] = useState('');
  const [imageBase64, setImageBase64] = useState('');
  const [generatedVideoUrl, setGeneratedVideoUrl] = useState('');
  const [videoBase64, setVideoBase64] = useState('');
  const [mediaType, setMediaType] = useState('image'); // 'image' or 'video'
  const [selectedPlatforms, setSelectedPlatforms] = useState(['linkedin']);
  const [isLoading, setIsLoading] = useState(false);
  const [isPublishing, setIsPublishing] = useState(false);
  const [notification, setNotification] = useState({ type: '', message: '' });
  const [confirmUrl, setConfirmUrl] = useState('');
  const [workflowStep, setWorkflowStep] = useState(1);
  const [hashtags, setHashtags] = useState([]);
  const [aiAssistantState, setAiAssistantState] = useState('ready');
  const [platformStatuses, setPlatformStatuses] = useState({});
  const [platformResults, setPlatformResults] = useState([]);
  const [isImageModalOpen, setIsImageModalOpen] = useState(false);

  useEffect(() => {
    if (generatedPost) {
      const hashtagRegex = /#[a-zA-Z0-9_]+/g;
      const extractedHashtags = generatedPost.match(hashtagRegex) || [];
      setHashtags(extractedHashtags.map(tag => tag.slice(1)));
    }
  }, [generatedPost]);

  const generatePost = async () => {
    if (!topic.trim()) {
      showNotification('error', 'Please enter a topic to generate a post.');
      return;
    }

    setIsLoading(true);
    setWorkflowStep(2);
    setAiAssistantState('generating');
    clearNotification();

    try {
      // Use the exact webhook URL from the workflow
      const webhookUrl = import.meta.env.VITE_N8N_WEBHOOK_GENERATE_POST;
      
      const response = await fetch(webhookUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ topic }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`HTTP error! status: ${response.status}, message: ${errorText}`);
      }

      const contentType = response.headers.get('content-type');
      if (!contentType || !contentType.includes('application/json')) {
        const text = await response.text();
        console.error('Unexpected response:', text);
        throw new Error('Server returned non-JSON response');
      }

      const text = await response.text();
      if (!text.trim()) {
        throw new Error('Server returned empty response - workflow may have failed');
      }

      let data;
      try {
        data = JSON.parse(text);
      } catch (jsonError) {
        console.error('JSON parsing failed:', jsonError, 'Response text:', text);
        throw new Error('Invalid JSON response from server');
      }
      console.log('Generated post data:', data);

      // The n8n workflow returns:
      // {
      //   "generatedPost": "...",        // The AI-generated post text
      //   "mediaType": "image" | "video", // Type of media generated
      //   "imageBase64": "...",           // Base64-encoded image (if image)
      //   "videoBase64": "...",           // Base64-encoded video (if video)
      //   "confirmUrl": "...",            // URL for publishing
      //   "message": "..."                // Success message
      // }
      const postContent = data.generatedPost || data.captionText || '';
      const detectedMediaType = data.mediaType || 'image';
      const imageBase64Data = data.imageBase64 || '';
      const videoBase64Data = data.videoBase64 || '';
      const confirmWebhookUrl = data.confirmUrl || '';
      
      if (!postContent || postContent.trim() === '') {
        console.error('No valid post content received:', data);
        throw new Error('No post content generated by AI. Please try again.');
      }

      console.log('Generated caption length:', postContent.length);
      console.log('Media type:', detectedMediaType);
      
      // Store the caption text
      setGeneratedPost(postContent);
      setMediaType(detectedMediaType);
      
      // Store the confirm URL for publishing
      if (confirmWebhookUrl) {
        setConfirmUrl(confirmWebhookUrl);
      }
      
      // Handle image or video based on media type
      if (detectedMediaType === 'video' && videoBase64Data) {
        console.log('Generated video base64 length:', videoBase64Data.length);
        
        // Store the base64 video data
        setVideoBase64(videoBase64Data);
        setImageBase64('');
        
        // Create the data URL for video preview
        const videoUrl = videoBase64Data.startsWith('data:video') 
          ? videoBase64Data 
          : `data:video/mp4;base64,${videoBase64Data}`;
        setGeneratedVideoUrl(videoUrl);
        setGeneratedImageUrl('');
      } else {
        // Handle image
        if (!imageBase64Data || imageBase64Data === 'filesystem-v2') {
          console.warn('No valid image data received');
        }
        
        console.log('Generated image base64 length:', imageBase64Data.length);
        
        // Store the base64 image data
        setImageBase64(imageBase64Data);
        setVideoBase64('');
        
        // Create the data URL for preview display
        if (imageBase64Data && imageBase64Data !== 'filesystem-v2') {
          const imageUrl = imageBase64Data.startsWith('data:image') 
            ? imageBase64Data 
            : `data:image/png;base64,${imageBase64Data}`;
          setGeneratedImageUrl(imageUrl);
          setGeneratedVideoUrl('');
        } else {
          setGeneratedImageUrl('');
        }
      }
      
      setWorkflowStep(3);
      setAiAssistantState('ready');
      const mediaTypeLabel = detectedMediaType === 'video' ? 'video' : 'image';
      showNotification('success', `✨ Post and ${mediaTypeLabel} generated successfully! Review and customize before publishing.`);
    } catch (error) {
      console.error('Error generating post:', error);
      setWorkflowStep(1);
      setAiAssistantState('error');
      showNotification('error', `Failed to generate post: ${error.message}`);
    } finally {
      setIsLoading(false);
    }
  };

  const uploadToCloudinary = async (base64Media, type = 'image') => {
    try {
      const cloudName = import.meta.env.VITE_CLOUDINARY_CLOUD_NAME;
      const uploadPreset = import.meta.env.VITE_CLOUDINARY_UPLOAD_PRESET;
      
      if (!cloudName || !uploadPreset) {
        throw new Error('Cloudinary credentials not configured. Please set VITE_CLOUDINARY_CLOUD_NAME and VITE_CLOUDINARY_UPLOAD_PRESET in .env');
      }

      // Ensure base64 has the data URL prefix
      let base64Data;
      if (type === 'video') {
        base64Data = base64Media.startsWith('data:video') 
          ? base64Media 
          : `data:video/mp4;base64,${base64Media}`;
      } else {
        base64Data = base64Media.startsWith('data:image') 
          ? base64Media 
          : `data:image/png;base64,${base64Media}`;
      }

      const formData = new FormData();
      formData.append('file', base64Data);
      formData.append('upload_preset', uploadPreset);

      // Use appropriate Cloudinary endpoint
      const endpoint = type === 'video' ? 'video' : 'image';
      const response = await fetch(
        `https://api.cloudinary.com/v1_1/${cloudName}/${endpoint}/upload`,
        {
          method: 'POST',
          body: formData,
        }
      );

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error?.message || 'Failed to upload to Cloudinary');
      }

      const data = await response.json();
      console.log(`✅ ${type === 'video' ? 'Video' : 'Image'} uploaded to Cloudinary:`, data.secure_url);
      return data.secure_url;
    } catch (error) {
      console.error('❌ Cloudinary upload failed:', error);
      throw new Error(`Cloudinary upload failed: ${error.message}`);
    }
  };

  const publishPost = async () => {
    if (!generatedPost.trim()) {
      showNotification('error', 'Please generate a post first.');
      return;
    }

    if (selectedPlatforms.length === 0) {
      showNotification('error', 'Please select at least one platform to publish to.');
      return;
    }

    setIsPublishing(true);
    setWorkflowStep(4);
    setAiAssistantState('publishing');
    clearNotification();
    
    // Initialize platform statuses
    const initialStatuses = {};
    selectedPlatforms.forEach(platform => {
      initialStatuses[platform] = 'publishing';
    });
    setPlatformStatuses(initialStatuses);

    const platformMapping = {
      'linkedin': 'linkedin',
      'facebook': 'facebook',
      'instagram': 'instagram'
    };

    try {
      // Upload media (image or video) to Cloudinary first if we have base64 data
      let cloudinaryMediaUrl = null;
      
      if (mediaType === 'video' && videoBase64) {
        console.log('📤 Uploading video to Cloudinary...');
        showNotification('info', '📤 Uploading video to cloud storage...');
        
        try {
          cloudinaryMediaUrl = await uploadToCloudinary(videoBase64, 'video');
          console.log('✅ Cloudinary Video URL:', cloudinaryMediaUrl);
        } catch (uploadError) {
          console.error('Cloudinary upload error:', uploadError);
          showNotification('error', `Video upload failed: ${uploadError.message}`);
          setIsPublishing(false);
          setWorkflowStep(3);
          setAiAssistantState('error');
          return;
        }
      } else if (imageBase64) {
        console.log('📤 Uploading image to Cloudinary...');
        showNotification('info', '📤 Uploading image to cloud storage...');
        
        try {
          cloudinaryMediaUrl = await uploadToCloudinary(imageBase64, 'image');
          console.log('✅ Cloudinary Image URL:', cloudinaryMediaUrl);
        } catch (uploadError) {
          console.error('Cloudinary upload error:', uploadError);
          showNotification('error', `Image upload failed: ${uploadError.message}`);
          setIsPublishing(false);
          setWorkflowStep(3);
          setAiAssistantState('error');
          return;
        }
      }

      // Prepare payload matching the workflow's expected format
      // The Confirm Webhook expects:
      // {
      //   "platforms": ["facebook", "instagram", "linkedin"],
      //   "post": "The generated post text",
      //   "imageUrl": "https://..." (for images)
      //   "videoUrl": "https://..." (for videos)
      // }
      const payload = {
        platforms: selectedPlatforms.map(p => platformMapping[p] || p),
        post: generatedPost,
      };

      // Add the Cloudinary media URL (prefer it over any existing URL)
      if (cloudinaryMediaUrl) {
        if (mediaType === 'video') {
          payload.videoUrl = cloudinaryMediaUrl;
        } else {
          payload.imageUrl = cloudinaryMediaUrl;
        }
      } else if (mediaType === 'video' && generatedVideoUrl && generatedVideoUrl.startsWith('http')) {
        payload.videoUrl = generatedVideoUrl;
      } else if (generatedImageUrl && generatedImageUrl.startsWith('http')) {
        payload.imageUrl = generatedImageUrl;
      }

      console.log('Publishing to platforms:', payload.platforms);
      console.log('Post length:', payload.post.length);
      console.log('Media type:', mediaType);
      console.log('Media URL:', payload.imageUrl || payload.videoUrl || 'none');

      // Use the environment variable or fallback - DO NOT use confirmUrl from workflow response
      // as it may point to the wrong n8n instance
      const confirmWebhookUrl = import.meta.env.VITE_N8N_WEBHOOK_CONFIRM_POST;
      
      console.log('🔵 Sending to webhook:', confirmWebhookUrl);
      console.log('🔵 Payload:', JSON.stringify(payload, null, 2));
      
      const response = await fetch(confirmWebhookUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });
      
      console.log('🔵 Response status:', response.status);
      
      if (!response.ok) {
        let errorMessage = `HTTP ${response.status}`;
        try {
          const errorData = await response.text();
          console.error('❌ Server error response:', errorData);
          errorMessage = errorData || errorMessage;
        } catch (e) {
          console.error('❌ Could not read error response');
        }
        throw new Error(`Webhook failed: ${errorMessage}`);
      }
      
      const result = await response.json();
      console.log('✅ Publishing response:', result);

      // Handle the structured response from Build Response node
      // Expected format:
      // {
      //   "status": "success" | "partial_success",
      //   "message": "...",
      //   "totalPlatforms": 3,
      //   "successCount": 3,
      //   "errorCount": 0,
      //   "platforms": [
      //     { "platform": "linkedin", "status": "success", "message": "...", "details": {...} },
      //     { "platform": "facebook", "status": "error", "message": "...", "details": {...} }
      //   ]
      // }

      // Store detailed platform results
      if (result.platforms && Array.isArray(result.platforms)) {
        setPlatformResults(result.platforms);
      }

      // Update platform statuses based on actual results
      const updatedStatuses = {};
      if (result.platforms && Array.isArray(result.platforms)) {
        result.platforms.forEach(platformResult => {
          const platformName = platformResult.platform;
          updatedStatuses[platformName] = platformResult.status === 'success' ? 'success' : 'error';
        });
      } else {
        // Fallback: assume all succeeded if no detailed info
        selectedPlatforms.forEach(platform => {
          updatedStatuses[platform] = 'success';
        });
      }
      setPlatformStatuses(updatedStatuses);

      // Determine overall success
      const allSuccess = result.status === 'success' || result.errorCount === 0;
      const successCount = result.successCount || 0;
      const errorCount = result.errorCount || 0;

      if (allSuccess) {
        setWorkflowStep(5);
        setAiAssistantState('success');
        showNotification(
          'success', 
          `🎉 ${result.message || `Successfully published to ${successCount} platform(s)!`}`
        );
      } else {
        // Partial success
        setWorkflowStep(4);
        setAiAssistantState('error');
        showNotification(
          'warning', 
          `⚠️ Partial success: ${successCount} published, ${errorCount} failed. Check platform details below.`
        );
      }
      
      // Reset form after 5 seconds (give user time to see results)
      setTimeout(() => {
        setTopic('');
        setGeneratedPost('');
        setGeneratedImageUrl('');
        setImageBase64('');
        setGeneratedVideoUrl('');
        setVideoBase64('');
        setMediaType('image');
        setConfirmUrl('');
        setWorkflowStep(1);
        setHashtags([]);
        setAiAssistantState('ready');
        setPlatformStatuses({});
        setPlatformResults([]);
      }, 5000);
    } catch (error) {
      console.error('Publishing error:', error);
      
      // Mark platforms as failed
      const failedStatuses = {};
      selectedPlatforms.forEach(platform => {
        failedStatuses[platform] = 'error';
      });
      setPlatformStatuses(failedStatuses);
      
      setWorkflowStep(3);
      setAiAssistantState('error');
      showNotification('error', `Failed to publish post: ${error.message}`);
    } finally {
      setIsPublishing(false);
    }
  };

  const handlePlatformChange = (platformId) => {
    setSelectedPlatforms(prev => 
      prev.includes(platformId) 
        ? prev.filter(p => p !== platformId)
        : [...prev, platformId]
    );
  };

  const showNotification = (type, message) => {
    setNotification({ type, message });
  };

  const clearNotification = () => {
    setNotification({ type: '', message: '' });
  };

  return (
    <div className="min-h-screen w-full bg-linear-to-br from-gray-900 to-gray-900 relative overflow-x-hidden">
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-pink-500/5 rounded-full blur-3xl animate-pulse"></div>
      </div>

      <div className="relative z-10 w-full max-w-full py-8 px-4 sm:px-6 lg:px-8 xl:px-12 overflow-x-hidden">
        {/* Top Navigation Bar */}
        <div className="flex items-center justify-between mb-8 px-2">
          {/* Left side - empty for balance */}
          <div className="w-48"></div>
          
          {/* Center - App Title */}
          <div className="flex-1 text-center">
            <h1 className="text-5xl font-bold bg-linear-to-r from-cyan-400 via-purple-400 to-pink-400 bg-clip-text text-transparent mb-4 tracking-tight">
              🚀 AI Social Automation Hub
            </h1>
            <p className="text-xl text-gray-300 mb-2">
              Generate • Customize • Publish • Automate
            </p>
            <div className="flex items-center justify-center space-x-4 text-sm text-gray-400">
              <div className="flex items-center">
                <div className="w-2 h-2 bg-green-400 rounded-full mr-2 animate-pulse"></div>
                AI-Powered Content Generation
              </div>
              <div className="flex items-center">
                <div className="w-2 h-2 bg-cyan-400 rounded-full mr-2 animate-pulse"></div>
                Multi-Platform Publishing
              </div>
              <div className="flex items-center">
                <div className="w-2 h-2 bg-purple-400 rounded-full mr-2 animate-pulse"></div>
                Real-time Automation
              </div>
            </div>
          </div>
          
          {/* Right side - User Profile with proper padding */}
          <div className="w-48 flex justify-end pr-4">
            <UserProfile />
          </div>
        </div>

        <WorkflowVisualization 
          currentStep={workflowStep}
          isGenerating={isLoading}
          isPublishing={isPublishing}
        />

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-4 lg:gap-6 xl:gap-8">
          <div className="lg:col-span-1 flex flex-col space-y-6">
            <div className="bg-gray-900/60 backdrop-blur-md rounded-2xl border border-cyan-500/30 shadow-xl p-6 group hover:border-cyan-400/50 transition-all duration-300 flex-1">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-xl font-bold bg-linear-to-r from-cyan-400 to-purple-400 bg-clip-text text-transparent">
                  Content Topic
                </h3>
                <div className="text-xs text-cyan-400 font-medium bg-cyan-400/10 px-2 py-1 rounded-full">
                  STEP 1
                </div>
              </div>
              
              <div className="relative">
                <input
                  type="text"
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  placeholder="✨ Enter your content idea..."
                  className="w-full p-4 bg-gray-800/50 backdrop-blur-sm border border-gray-600/50 rounded-xl text-gray-200 placeholder-gray-500 focus:ring-2 focus:ring-cyan-500 focus:border-transparent transition-all duration-300"
                  disabled={isLoading}
                  onKeyPress={(e) => e.key === 'Enter' && generatePost()}
                />
                {topic && (
                  <div className="absolute top-2 right-2 px-2 py-1 bg-cyan-400/20 border border-cyan-400/30 rounded-full text-xs text-cyan-400 font-medium">
                    {topic.length} chars
                  </div>
                )}
              </div>
              
              {/* Media Type Hint */}
              <div className="mt-3 p-3 bg-gray-800/30 rounded-lg border border-gray-700/30">
                <div className="text-xs text-gray-400 flex items-center">
                  <span className="mr-2">💡</span>
                  <span>
                    Tip: Include "video" in your topic for AI-generated videos (Veo 2.0), or leave it for images (Imagen 4.0)
                  </span>
                </div>
              </div>
              
              <div className="mt-6 flex space-x-3">
                <button
                  onClick={generatePost}
                  disabled={isLoading}
                  className="flex-1 bg-linear-to-r from-purple-600 to-cyan-600 text-white py-4 px-6 rounded-xl hover:from-purple-500 hover:to-cyan-500 disabled:from-gray-600 disabled:to-gray-700 disabled:cursor-not-allowed transition-all duration-300 font-semibold text-sm hover:scale-[1.02] active:scale-[0.98]"
                >
                  {isLoading ? (
                    <LoadingSpinner text="AI Generating" className="justify-center" />
                  ) : (
                    <div className="flex items-center justify-center">
                      <span className="mr-2">🤖</span>
                      Generate Post
                    </div>
                  )}
                </button>
                
                {generatedPost && (
                  <button
                    onClick={generatePost}
                    disabled={isLoading}
                    className="bg-gray-700/50 backdrop-blur-sm text-gray-300 py-4 px-6 rounded-xl hover:bg-gray-600/50 disabled:bg-gray-800/50 disabled:cursor-not-allowed transition-all duration-300 font-medium text-sm border border-gray-600/50 hover:border-gray-500/50"
                  >
                    🔄 Regenerate
                  </button>
                )}
              </div>
            </div>

            <div className="flex-1">
              <PlatformSelector 
                platforms={selectedPlatforms}
                onPlatformChange={handlePlatformChange}
              />
            </div>
          </div>

          <div className="lg:col-span-3 space-y-6">
            <PostPreview 
              post={generatedPost}
              onPostChange={(e) => setGeneratedPost(e.target.value)}
              hashtags={hashtags}
              imageUrl={generatedImageUrl}
              videoUrl={generatedVideoUrl}
              mediaType={mediaType}
              onModalChange={setIsImageModalOpen}
            />

            {generatedPost && (
              <div className="bg-gray-900/60 backdrop-blur-md rounded-2xl border border-green-500/30 shadow-xl p-6 hover:border-green-400/50 transition-all duration-300">
                {/* Platform Status Indicators with Detailed Results */}
                {Object.keys(platformStatuses).length > 0 && (
                  <div className="mb-4 p-4 bg-gray-800/50 rounded-xl border border-gray-700/50">
                    <div className="text-sm font-medium text-gray-300 mb-3 flex items-center">
                      <span className="mr-2">📡</span>
                      Publishing Status
                    </div>
                    <div className="space-y-3">
                      {platformResults.length > 0 ? (
                        // Show detailed results from Build Response node
                        platformResults.map((result) => (
                          <div key={result.platform} className="bg-gray-900/50 rounded-lg p-3 border border-gray-700/30">
                            <div className="flex items-center justify-between mb-1">
                              <div className="flex items-center space-x-2">
                                <span className="text-sm font-medium capitalize text-gray-300">
                                  {result.platform === 'linkedin' && '💼 LinkedIn'}
                                  {result.platform === 'facebook' && '📘 Facebook'}
                                  {result.platform === 'instagram' && '📸 Instagram'}
                                </span>
                              </div>
                              <div className="flex items-center space-x-2">
                                {result.status === 'success' && (
                                  <>
                                    <div className="w-2 h-2 bg-green-400 rounded-full"></div>
                                    <span className="text-xs text-green-400 font-medium">✓ Published</span>
                                  </>
                                )}
                                {result.status === 'error' && (
                                  <>
                                    <div className="w-2 h-2 bg-red-400 rounded-full"></div>
                                    <span className="text-xs text-red-400 font-medium">✗ Failed</span>
                                  </>
                                )}
                              </div>
                            </div>
                            <div className="text-xs text-gray-400 mt-1">
                              {result.message}
                            </div>
                            {result.status === 'error' && result.details && (
                              <div className="text-xs text-red-400/80 mt-1 italic">
                                Error: {result.details.message || JSON.stringify(result.details)}
                              </div>
                            )}
                          </div>
                        ))
                      ) : (
                        // Show simple status during publishing
                        Object.entries(platformStatuses).map(([platform, status]) => (
                          <div key={platform} className="flex items-center justify-between">
                            <div className="flex items-center space-x-2">
                              <span className="text-sm capitalize text-gray-300">
                                {platform === 'linkedin' && '💼 LinkedIn'}
                                {platform === 'facebook' && '📘 Facebook'}
                                {platform === 'instagram' && '📸 Instagram'}
                              </span>
                            </div>
                            <div className="flex items-center space-x-2">
                              {status === 'publishing' && (
                                <>
                                  <div className="w-2 h-2 bg-blue-400 rounded-full animate-pulse"></div>
                                  <span className="text-xs text-blue-400">Publishing...</span>
                                </>
                              )}
                              {status === 'success' && (
                                <>
                                  <div className="w-2 h-2 bg-green-400 rounded-full"></div>
                                  <span className="text-xs text-green-400">✓ Published</span>
                                </>
                              )}
                              {status === 'error' && (
                                <>
                                  <div className="w-2 h-2 bg-red-400 rounded-full"></div>
                                  <span className="text-xs text-red-400">✗ Failed</span>
                                </>
                              )}
                            </div>
                          </div>
                        ))
                      )}
                    </div>
                  </div>
                )}
                
                <button
                  onClick={publishPost}
                  disabled={isPublishing || selectedPlatforms.length === 0}
                  className="w-full bg-linear-to-r from-green-600 to-emerald-600 text-white py-6 px-8 rounded-xl hover:from-green-500 hover:to-emerald-500 disabled:from-gray-600 disabled:to-gray-700 disabled:cursor-not-allowed transition-all duration-300 font-bold text-lg hover:scale-[1.01] active:scale-[0.99] group"
                >
                  {isPublishing ? (
                    <LoadingSpinner text="Publishing to platforms" className="justify-center" />
                  ) : (
                    <div className="flex items-center justify-center space-x-3">
                      <span className="text-2xl group-hover:animate-bounce">🚀</span>
                      <div>
                        <div>Publish to {selectedPlatforms.length} Platform{selectedPlatforms.length > 1 ? 's' : ''}</div>
                        <div className="text-sm opacity-80 font-normal">
                          {selectedPlatforms.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join(' • ')}
                        </div>
                      </div>
                    </div>
                  )}
                </button>
              </div>
            )}
          </div>
        </div>

        <div className="mt-16 text-center">
          <div className="inline-flex items-center space-x-4 bg-gray-900/50 backdrop-blur-md rounded-full px-6 py-3 border border-gray-700/50">
            <div className="flex items-center space-x-2">
              <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></div>
              <span className="text-sm text-gray-400">Powered by</span>
            </div>
            <span className="text-sm font-medium bg-linear-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent">
              Aziona Automation & AI
            </span>
          </div>
        </div>
      </div>

      <ToastNotification 
        type={notification.type} 
        message={notification.message} 
        onClose={clearNotification} 
      />

      <AIAssistant 
        isGenerating={isLoading}
        isPublishing={isPublishing}
        lastAction={notification.type}
        isModalOpen={isImageModalOpen}
      />
    </div>
  );
};

export default Dashboard;